// ================================== *
//   Copyright Xialia.com  2011-2016
//   FILE : src/drumee/lex/picto
//   TYPE : Mandatory definitions
// ================================== *


const a = {
  address             : 'home',
  align               : {
    _                 : "exchange",
    left              : 'align-left',
    right             : 'align-right',
    center            : 'align-center',
    justify           : 'align-justify'
  },

  angle               : {
    space_around      : 'square-o',
    space_between     : 'columns',
    top               : 'angle-up',
    bottom            : 'angle-down',
    center            : 'plus-square-o',
    center_v          : 'arrows-v',
    center_h          : 'arrows-h',
    left              : 'angle-left',
    right             : 'angle-right'
  },
  arrows              : {
    both              : 'arrows',
    h                 : 'arrows-h',
    v                 : 'arrows-v'
  },
  audio               : "file-audio-o",
  back                : 'angle-left',
  'background-color'  : 'paint-brush',
  ban                 : 'ban',
  bars                : 'bars',
  bold                : 'bold',
  bomb                : 'bomb',
  book                : 'book',
  brush               : 'paint-brush',

  camera              : 'camera',
  cancel              : 'ban',
  caret               : {
    each_side         : 'arrows',
    top               : 'caret-square-o-up',
    bottom            : 'caret-square-o-down',
    left              : 'caret-square-o-left',
    right             : 'caret-square-o-right'
  },
  chart               : {
    area              : 'area-chart',
    bar               : 'bar-chart',
    line              : 'line-chart',
    pie               : 'pie-chart'
  },
  check_circle        : 'check-circle',
  check_square        : 'check-square-o',
  circle_o            : 'circle-o',
  circle_thin         : 'circle-thin',
  clipboard           : 'clipboard',
  clock               : 'clock-o',
  clone               : 'clone',
  cloud               : 'cloud',
  cloud_download      : 'cloud-download',
  cloud_upload        : 'cloud-upload',
  code                : "code",
  color               : 'paint-brush',
  columns             : "columns",
  comment_o           : "comment-o",
  comments_o          : "comments-o",
  content             : "file-o",
  copyStyle           : "paint-brush",
  css3                : "css3",

  dedent              : 'dedent',
  desktop             : 'desktop',
  devMode             : "terminal",
  dmail               : 'envelope',
  doc                 : "file-word-o",
  docx                : "file-word-o",
  dot_circle_o        : 'dot-circle-o',
  download            : "download",
  edit                : 'edit',
  email               : 'envelope',
  empty               : 'eraser',
  eraser              : "eraser",
  excel               : "file-excel-o",
  exchange            : "exchange",
  exe                 : "warning",
  exponent            : 'superscript',
  expand              : "expand",
  external_link       : "external-link",
  eye                 : "eye",
  eye_slash           : "eye-slash",
  file                : "file-o",
  files               : 'files-o',
  film                : "film",
  firstname           : 'user',
  flag                : "flag-o",
  floppy              : "floppy-o",
  folder              : "folder-o",
  font                : "font",
  href                : "external-link",
  gear                : 'gear',
  gears               : 'gears',
  group               : 'group',
  hashtag             : 'hashtag',
  handOright          : "hand-o-right",
  headline            : 'home',
  home                : 'home',
  hide                : 'angle-left',
  image               : {
    comment           : 'comment-o',
    player            : 'images'
  },
  indent              : 'indent',
  info                : 'info',
  info_circle         : 'info-circle',
  italic              : 'italic',
  ident               : 'user',
  'justify-content'   : 'align-justify',

  key                 : 'key',
  lastname            : 'user',
  laptop              : 'laptop',
  level_up            : "level-up",
  link                : "link",
  list                : "list",
  list_alt            : "list-alt",
  lock                : "lock",
  logout              : "power-off",

  magic               : 'magic',
  magnet              : 'magnet',
  margin              : "square-o",
  'margin-left'       : 'angle-left',
  'margin-right'      : 'angle-right',
  'margin-top'        : 'angle-up',
  'margin-bottom'     : 'angle-down',
  mobile              : 'mobile-phone',
  music               : 'music',

  news                : 'newspaper-o',

  other               : "file-o",

  paint_brush         : 'paint-brush',
  padding             : "square-o",
  'padding-left'      : 'angle-left',
  'padding-right'     : 'angle-right',
  'padding-top'       : 'angle-up',
  'padding-bottom'    : 'angle-down',
  paper_plane_o       : 'paper-plane-o',
  params              : 'gear',
  pdf                 : "file-pdf-o",
  pencil              : "pencil",
  pending             : "spinner fa-spin",
  phone               : 'phone',
  photo               : 'user',
  photo_prv           : 'user',
  photo_pub           : 'user',
  photo_res           : 'user',
  picture             : 'picture-o',
  plane               : 'plane',
  play                : 'play',
  plug                : 'plug',
  plus                : 'plus',
  plus_square         : 'plus-square',
  plus_square_o       : 'plus-square-o',
  power_off           : "power-off",
  ppt                 : "file-powerpoint-o",
  pptx                : "file-powerpoint-o",
  preview             : "eye",

  question            : "question",
  question_circle     : "question-circle",

  rar                 : "file-zip-o",
  redo                : "repeat",
  refresh             : "refresh",
  remove              : "times",
  repeat              : "repeat",
  rotate_left         : "rotate-left",
  rotate_right        : "rotate-right",
  rss                 : "rss",

  save                : "floppy-o",
  search              : "search",
  security            : "lock",
  share               : "share",
  share_alt           : "share-alt",
  show                : "angle-right",
  sortAsc             : "sort-asc",
  sortDesc            : "sort-desc",
  source              : "external-link",
  spinner             : "spinner fa-spin",
  square              : 'square-o',
  stop                : 'stop',
  styleOpt            : 'css3',
  submit              : 'send',
  sun_o               : 'sun-o',
  superscript         : 'superscript',

  table               : "table",
  tablet              : "tablet",
  tag                 : "tag",
  tags                : "tags",
  terminal            : "terminal",
  text                : "file-text-o",
  thumbs_up           : "thumbs-o-up",
  times               : "times",
  tint                : "tint",
  toggle_off          : "toggle-off",
  toggle_on           : "toggle-on",
  trash               : "trash-o",
  trashOn             : "trash-o",
  trashOff            : "trash",
  tv                  : "tv",
  twitter             : "twitter",
  underline           : "underline",
  undo                : "undo",
  unlock              : "unlock",
  unknown             : 'exclamation-circle',
  user                : 'user',
  userAttributes      : 'html5',
  userClass           : 'code',
  user_plus           : 'user-plus',
  user_times          : 'user-times',
  users               : 'users',
  video               : {
    camera            : 'video-camera',
    comment           : 'comment-o',
    native            : 'video-camera',
    player            : 'play-circle',
    thread            : 'list'
  },
  warning             : "warning",
  word                : "file-word-o",
  wrench              : "wrench",
  xls                 : "file-excel-o",
  zip                 : "file-zip-o"
};


for (let k in a) {
  const v = a[k];
  if (_.isString(v)) {
    a[k] = `fa fa-${v} fa-fw`;
  } else if (_.isObject(v)) {
    for (let q in v) {
      const r = v[q];
      a[k][q] = `fa fa-${r} fa-fw`;
    }
  }
}

module.exports = a;
