// ------------------------------------------------------------------- 
// Automatically generated by locale.rpc on 2017/04/01 23:42:14
// MODULE NAME _RPC
// DO NOT EDIT !!!
// ------------------------------------------------------------------- 
const _RPC = { 
  page: {
    logout:'page.logout',
    lang:'page.lang',
    default:'page.default',
    home:'page.home'
  },
  admin: {
    ping:'admin.ping'
  },
  comment: {
    list:'comment.list',
    read:'comment.read'
  },
  req: {
    login:'req.login',
    logout:'req.logout',
    contact:'req.contact',
    presub:'req.presub',
    lostpw:'req.lostpw',
    resetpw:'req.resetpw',
    register:'req.register',
    signon:'req.signon',
    presignon:'req.presignon',
    webmaster:'req.webmaster',
    myhubs:'req.myhubs',
    guest:'req.guest',
    ping:'req.ping',
    error:'req.error',
    get_style:'req.get_style'
  },
  style: {
    list:'style.list',
    search:'style.search',
    get_all:'style.get_all',
    get_classes:'style.get_classes',
    get_files:'style.get_files',
    get:'style.get'
  },
  hub: {
    photo:'hub.photo',
    info:'hub.info',
    show_hubers:'hub.show_hubers'
  },
  community: {
    photo:'community.photo',
    info:'community.info',
    show_hubers:'community.show_hubers'
  },
  poll: {
    submit:'poll.submit'
  },
  drumate: {
    photo:'drumate.photo',
    profile:'drumate.profile',
    info:'drumate.info'
  },
  media: {
    audio:'media.audio',
    best:'media.best',
    card:'media.card',
    chvw:'media.chvw',
    dld:'media.dld',
    fet:'media.fet',
    frt:'media.frt',
    ftnw:'media.ftnw',
    ftr:'media.ftr',
    gallery:'media.gallery',
    gtgl:'media.gtgl',
    ltr:'media.ltr',
    orig:'media.orig',
    search:'media.search',
    show:'media.show',
    showBy:'media.showBy',
    show_slides:'media.show_slides',
    slide:'media.slide',
    theme:'media.theme',
    thread:'media.thread',
    thumb:'media.thumb',
    video:'media.video',
    vignette:'media.vignette',
    webp:'media.webp'
  },
  layout: {
    get:'layout.get',
    update:'layout.update',
    save:'layout.save',
    add:'layout.add',
    list:'layout.list',
    remove:'layout.remove',
    retrieve:'layout.retrieve',
    purge:'layout.purge',
    search:'layout.search',
    set_as_homepage:'layout.set_as_homepage'
  },
  gallery: {
    photos:'gallery.photos'
  },
  lookup: {
    profile:'lookup.profile'
  },
  blog: {
    threads:'blog.threads',
    articles:'blog.articles'
  },
  site: {
    list_hubers:'site.list_hubers'
  },
  search: {
    drumate:'search.drumate',
    user:'search.user',
    hub:'search.hub',
    lang:'search.lang'
  },
  yp: {
    hubs:'yp.hubs',
    drumates:'yp.drumates',
    search_drumate:'yp.search_drumate',
    email_exists:'yp.email_exists',
    ident_exists:'yp.ident_exists',
    lookup_language:'yp.lookup_language',
    lookup_country:'yp.lookup_country',
    lookup_city:'yp.lookup_city',
    lookup_hub:'yp.lookup_hub',
    suggest_ident:'yp.suggest_ident'
  },
  costum: {
    flow1:'costum.flow1',
    flow2:'costum.flow2',
    beacons:'costum.beacons',
    tracks:'costum.tracks'
  }
};
module.exports = _RPC;
