// ------------------------------------------------------------------- 
// Automatically generated by locale.rpc on 2017/04/01 23:42:14
// MODULE NAME _RPC
// DO NOT EDIT !!!
// ------------------------------------------------------------------- 
const _RPC = { 
  page: {
    slg:'page.slg',
    home:'page.home'
  },
  req: {
    login:'req.login',
    logout:'req.logout',
    myhubs:'req.myhubs',
    mysites:'req.mysites',
    list_drumates:'req.list_drumates',
    signon:'req.signon',
    presignon:'req.presignon',
    register:'req.register',
    webmaster:'req.webmaster',
    contact:'req.contact',
    guest:'req.guest',
    ping:'req.ping',
    error:'req.error',
    get_style:'req.get_style'
  },
  style: {
    list:'style.list',
    search:'style.search',
    get_all:'style.get_all',
    get_classes:'style.get_classes',
    get_files:'style.get_files',
    get:'style.get',
    add:'style.add',
    save:'style.save',
    remove:'style.remove'
  },
  feed: {
    twitter:'feed.twitter',
    rss:'feed.rss'
  },
  community: {
    set_profile:'community.set_profile',
    create:'community.create',
    photo:'community.photo',
    info:'community.info',
    request:'community.request',
    purge:'community.purge',
    show_hubers:'community.show_hubers',
    update:'community.update',
    set_privilege:'community.set_privilege',
    add_huber:'community.add_huber',
    withdraw:'community.withdraw',
    join:'community.join'
  },
  hub: {
    set_profile:'hub.set_profile',
    create:'hub.create',
    copy:'hub.copy',
    photo:'hub.photo',
    info:'hub.info',
    request:'hub.request',
    purge:'hub.purge',
    show_hubers:'hub.show_hubers',
    update:'hub.update',
    set_privilege:'hub.set_privilege',
    add_huber:'hub.add_huber',
    withdraw:'hub.withdraw',
    save:'hub.save',
    remove:'hub.remove',
    join:'hub.join'
  },
  poll: {
    submit:'poll.submit'
  },
  drumate: {
    set_profile:'drumate.set_profile',
    photo:'drumate.photo',
    profile:'drumate.profile',
    info:'drumate.info',
    closest:'drumate.closest',
    change_pw:'drumate.change_pw',
    update:'drumate.update'
  },
  media: {
    audio:'media.audio',
    best:'media.best',
    browse:'media.browse',
    caption:'media.caption',
    card:'media.card',
    comment:'media.comment',
    gallery:'media.gallery',
    h264:'media.h264',
    mkPublic:'media.mkPublic',
    mkdir:'media.mkdir',
    ogv:'media.ogv',
    orig:'media.orig',
    photo:'media.photo',
    remove:'media.remove',
    rename:'media.rename',
    replace:'media.replace',
    retrieve:'media.retrieve',
    rm_comment:'media.rm_comment',
    rotate:'media.rotate',
    search:'media.search',
    show:'media.show',
    showBy:'media.showBy',
    show_all:'media.show_all',
    show_dir:'media.show_dir',
    show_slides:'media.show_slides',
    slide:'media.slide',
    slurp:'media.slurp',
    suggest_folder:'media.suggest_folder',
    theme:'media.theme',
    thread:'media.thread',
    thumb:'media.thumb',
    trash:'media.trash',
    update_status:'media.update_status',
    upload:'media.upload',
    video:'media.video',
    vignette:'media.vignette',
    webp:'media.webp'
  },
  layout: {
    add:'layout.add',
    copy:'layout.copy',
    get:'layout.get',
    list:'layout.list',
    lock:'layout.lock',
    purge:'layout.purge',
    remove:'layout.remove',
    retrieve:'layout.retrieve',
    save:'layout.save',
    search:'layout.search',
    set_as_homepage:'layout.set_as_homepage',
    unlock:'layout.unlock',
    update:'layout.update',
    new:'layout.new',
    store:'layout.store',
    backup:'layout.backup',
    preview:'layout.preview'
  },
  admin: {
    add_user:'admin.add_user',
    add_hub:'admin.add_hub',
    remove:'admin.remove',
    purge:'admin.purge',
    retrieve:'admin.retrieve',
    lookup:'admin.lookup',
    admin:'admin.admin',
    spaces:'admin.spaces',
    users:'admin.users',
    hubs:'admin.hubs',
    managed:'admin.managed',
    update_user:'admin.update_user',
    update_site:'admin.update_site',
    drumates:'admin.drumates',
    reset_password:'admin.reset_password',
    add_huber:'admin.add_huber',
    set_privilege:'admin.set_privilege',
    remove_huber:'admin.remove_huber',
    show_hubers:'admin.show_hubers'
  },
  comment: {
    post:'comment.post',
    list:'comment.list',
    read:'comment.read'
  },
  search: {
    drumate:'search.drumate',
    user:'search.user',
    hub:'search.hub',
    lang:'search.lang'
  },
  yp: {
    hubs:'yp.hubs',
    ident_exists:'yp.ident_exists',
    email_exists:'yp.email_exists',
    lookup_language:'yp.lookup_language',
    lookup_country:'yp.lookup_country',
    lookup_city:'yp.lookup_city',
    lookup_drumate:'yp.lookup_drumate',
    lookup_hub:'yp.lookup_hub',
    suggest_ident:'yp.suggest_ident'
  },
  costum: {
    flow1:'costum.flow1',
    flow2:'costum.flow2',
    beacons:'costum.beacons',
    all_flow:'costum.all_flow',
    tracks:'costum.tracks'
  }
};
module.exports = _RPC;
